feat: added storybook and first component
KoTuK2306/reactApp pull request #1
Opened 2022-02-14 17:39 UTC by KoTuK2306

2022-02-14 20:41 UTC, pavelsokolov21 commented on .storybook/preview.js
> +}
добавь пробел

2022-02-14 20:41 UTC, pavelsokolov21 commented on src/components/UI-Kit/UIButton/UIButton.jsx
> +  return <button className={cn(classes[props.variant])}>{props.text}</button>;
тут нет смысла использовать `cn`

2022-02-14 20:41 UTC, pavelsokolov21 commented on src/components/UI-Kit/UIButton/UIButton.jsx
> +  return <button className={cn(classes[props.variant])}>{props.text}</button>;
контент кнопки можно передавать как `children` ([почитай](https://reactjs.org/docs/composition-vs-inheritance.html), если не знаешь).  Так в кнопку можно будет передавать не только текст, но и другие React-элементы

2022-02-14 20:41 UTC, pavelsokolov21 commented on src/stories/Button.stories.js
> +export const Standart = () => <UIButton text="Standart" variant="standart" />;
По-моему, в Storybook можно добавить опцию, которая позволяет переключать пропсы динамически через UI. Так тебе не нужно будет создавать три отдельные стори под разные пропсы компонента.
Вроде как, это тот самый [аддон](https://github.com/storybookjs/storybook/tree/master/addons/knobs)

2022-02-14 20:47 UTC, pavelsokolov21 commented on src/stories/Button.stories.js
> +import { UIButton } from "../components/UI-Kit/UIButton";
хорошей практикой является создание сторифайла рядом с компонентом, а не в отдельной папке

2022-02-14 20:47 UTC, pavelsokolov21 commented on src/components/UI-Kit/UIButton/UIButton.jsx
> +  text: PropTypes.string,
require props

2022-02-15 09:20 UTC, pavelsokolov21 commented on storybook-static/iframe.html
> +<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Webpack App</title><meta name="viewport" content="width=device-width,initial-scale=1"><base target="_parent"><style>:not(.sb-show-pre
добавь папку `storybook-static` в gitignore

2022-02-15 09:20 UTC, pavelsokolov21 commented on package.json
> +    "storybook": "start-storybook -p 6006 -s public"
если у тебя чисто сторибук, то пусть этот скрипт будет являться стартом

2022-02-15 09:54 UTC, pavelsokolov21 requested changes

2022-02-15 09:54 UTC, pavelsokolov21 commented on src/components/UI-Kit/UIButton/Button.jsx
> +      {label}
`children`

2022-02-15 09:54 UTC, pavelsokolov21 commented on src/components/UI-Kit/UIButton/Button.jsx
> +  onClick: PropTypes.func,
выглядит так, что это `require`

2022-02-15 09:54 UTC, pavelsokolov21 commented on src/stories/Button.stories.js
> +import { Button } from "../components/UI-Kit/index";
по хорошим практикам, сторифайл создают рядом с компонентом, а не в отдельной папке

2022-02-15 09:54 UTC, pavelsokolov21 commented on src/stories/Stack.stories.js
> +    {[...Array(numberOfChildren).keys()].map((n) => (
зачем так сложно?

2022-02-15 09:54 UTC, pavelsokolov21 commented on src/stories/Stack.stories.js
> +        style={{
почему выбор пал на инлайн стили?

2022-02-15 09:54 UTC, pavelsokolov21 commented on src/components/UI-Kit/UIStack/Stack.jsx
> +  const style = {
если так хочешь использовать инлайн стили, то лучше юзай [styled-components](https://styled-components.com/)

2022-02-15 10:08 UTC, KoTuK2306 commented on src/stories/Stack.stories.js
> +        style={{
Это временная фича, в будущем это будет переделано

2022-02-15 11:18 UTC, pavelsokolov21 commented on src/components/UI-Kit/UIButton/Button.jsx
> +  children: PropTypes.any.isRequired,
не `any`

2022-02-15 11:18 UTC, pavelsokolov21 commented on src/components/UI-Kit/UIStack/Stack.stories.js
> +    {[...Array(numberOfChildren).keys()].map((n) => (
почему так сложно? Что такое `n`?

2022-02-15 11:18 UTC, pavelsokolov21 commented on src/components/UI-Kit/UIStack/Stack.jsx
> +Stack.propTypes = {
добавь `children`

2022-02-16 08:58 UTC, pavelsokolov21 commented on src/components/UI-Kit/UIStack/Stack.stories.js
> +        {"div"}
здесь должен быть просто текст без скобок

2022-02-16 08:58 UTC, pavelsokolov21 commented on src/components/UI-Kit/UIStack/Stack.stories.js
> +    {[...Array(numberOfChildren)].map(() => (
тут точно должен быть `Array`? Разве спред-оператора не достаточно?

2022-02-16 08:59 UTC, KoTuK2306 commented on src/components/UI-Kit/UIStack/Stack.stories.js
> +    {[...Array(numberOfChildren)].map(() => (
Без Array не работает почему-то

2022-02-16 09:07 UTC, pavelsokolov21 approved these changes

2022-02-16 09:08 UTC, merged