feat: added simple buttonsGroup
KoTuK2306/reactApp pull request #4
Opened 2022-02-18 14:32 UTC by KoTuK2306

2022-02-18 14:39 UTC, pavelsokolov21 commented on src/components/UI-Kit/UIButtonGroup/ButtonGroup.stories.js
> +  children: ["one", "two"],
В данном случае это не является children. Это просто набор данных, на основе которых ты создаешь массив JSX'в

2022-02-18 14:39 UTC, pavelsokolov21 commented on src/components/UI-Kit/UIButtonGroup/ButtonGroup.jsx
> +export const ButtonGroup = (children, backgroundColor = "red") => {
```suggestion
export const ButtonGroup = ({ items, backgroundColor = "red" }) => {}
```

2022-02-19 12:05 UTC, pavelsokolov21 requested changes

2022-02-19 12:05 UTC, pavelsokolov21 commented on src/components/UI-Kit/UIButton/Button.style.js
>    if (variant === "bordered" || variant === "text") return variant === "bordered" || variant === "text";
Ненужный if

2022-02-19 12:05 UTC, pavelsokolov21 commented on src/components/UI-Kit/UIButtonGroup/ButtonGroup.jsx
> +   * Choose size of your button
Разве есть смысл в комментах?

2022-02-19 12:05 UTC, pavelsokolov21 commented on src/components/UI-Kit/UIButtonGroup/ButtonGroup.stories.js
> +import { ButtonGroup } from "./index";
Лучше из самого компонента импортировать

2022-02-19 12:05 UTC, pavelsokolov21 commented on src/components/UI-Kit/UIButtonGroup/ButtonGroup.style.js
> +import { darken, rgba, lighten } from "polished";
Сначала библиотеки, потом компоненты

2022-02-19 12:05 UTC, pavelsokolov21 commented on src/components/UI-Kit/UIButtonGroup/ButtonGroup.style.js
> +const leftRightBorder = (func, coefficient, color, size) => `${size}px solid ${func(coefficient, color)}`;
Думаю, просто getBorderStyle

2022-02-19 12:05 UTC, pavelsokolov21 commented on src/components/UI-Kit/index.js
> +export { ButtonGroup } from "./UIButtonGroup/index";
Импорт/экспорт из index не обязательно указывать, достаточно просто папки

2022-02-19 12:20 UTC, KoTuK2306 commented on src/components/UI-Kit/UIButtonGroup/ButtonGroup.jsx
> +   * Choose size of your button
Да, это в документации появляется как описание данной опции

2022-02-19 16:54 UTC, pavelsokolov21 commented on src/components/UI-Kit/index.js
> +export { Button } from "./UIButton/";
Последний слеш не нужен

2022-02-19 19:23 UTC, pavelsokolov21 approved these changes

2022-02-19 19:33 UTC, merged