feat: added SwitchableCheckbox without controling
KoTuK2306/reactApp pull request #5
Opened 2022-02-22 10:58 UTC by KoTuK2306

2022-02-22 11:15 UTC, pavelsokolov21 requested changes

2022-02-22 11:15 UTC, pavelsokolov21 commented on src/components/UI-Kit/UISwitchableCheckbox/SwitchableCheckbox.jsx
> +        Text for checkbox
проп для текста

2022-02-22 11:15 UTC, pavelsokolov21 commented on src/components/UI-Kit/UISwitchableCheckbox/SwitchableCheckbox.jsx
> +      <StyledLabel for="check" id="check">
через ID делать не рекомендую, тк если будет много таких компонентов, то нужно будет много уникальных ID. Лучше обернуть в `label` вместо использования `for`. [Пример](https://stackoverflow.com/a/7379073)

2022-02-22 11:15 UTC, pavelsokolov21 commented on src/components/UI-Kit/UISwitchableCheckbox/SwitchableCheckbox.style.js
> +    left: 2.5px;
0.5 так важно?

2022-02-22 11:15 UTC, pavelsokolov21 commented on src/components/UI-Kit/UISwitchableCheckbox/SwitchableCheckbox.style.js
> +    left: 43px;
Когда я вижу такие числа и позиционирования, я понимаю, что такие чекбоксы, скорее всего, не адаптивны. Лучше сделать с обернутым в `label` и через `flex/grid`

2022-02-22 11:15 UTC, pavelsokolov21 commented on src/components/UI-Kit/UISwitchableCheckbox/SwitchableCheckbox.style.js
> +    transform: translateX(0%);
просто `0` достаточно

2022-02-22 11:15 UTC, pavelsokolov21 commented on src/components/UI-Kit/UISwitchableCheckbox/SwitchableCheckbox.style.js
> +    background-color: grey;
везде `hex`

2022-02-22 11:15 UTC, pavelsokolov21 commented on src/components/UI-Kit/UISwitchableCheckbox/SwitchableCheckbox.style.js
> +  user-select: none;
зачем?

2022-02-22 11:15 UTC, pavelsokolov21 commented on src/components/UI-Kit/UISwitchableCheckbox/SwitchableCheckbox.style.js
> +    background-color: purple;
hex

2022-02-22 11:16 UTC, KoTuK2306 commented on src/components/UI-Kit/UISwitchableCheckbox/SwitchableCheckbox.style.js
> +  user-select: none;
Иначе при нажатии на текст н выделялся постянно

2022-02-22 11:18 UTC, KoTuK2306 commented on src/components/UI-Kit/UISwitchableCheckbox/SwitchableCheckbox.style.js
> +    left: 2.5px;
Иначе мне режет глаз неровнсть

2022-02-22 11:21 UTC, pavelsokolov21 commented on src/components/UI-Kit/UISwitchableCheckbox/SwitchableCheckbox.style.js
> +    left: 2.5px;
такие сдвиги выглядят просто как хардкод. Лучше сделать через `flex/grid`

2022-02-25 08:41 UTC, pavelsokolov21 approved these changes

2022-02-25 09:28 UTC, merged