feat: added new component slider
KoTuK2306/reactApp pull request #9
Opened 2022-02-28 22:04 UTC by KoTuK2306

2022-02-28 22:17 UTC, pavelsokolov21 requested changes

2022-02-28 22:17 UTC, pavelsokolov21 commented on src/components/UI-Kit/UISlider/Slider.jsx
> +/* eslint-disable react/jsx-no-duplicate-props */
Зачем?

2022-02-28 22:17 UTC, pavelsokolov21 commented on src/components/UI-Kit/UISlider/Slider.jsx
> +import React, { useState } from "react";
Сейчас `React` импортировать не надо

2022-02-28 22:17 UTC, pavelsokolov21 commented on src/components/UI-Kit/UISlider/Slider.jsx
> +  const [num, setNum] = useState(50);
`num` - это слишком абстрактно. Придумай название лучше

2022-02-28 22:17 UTC, pavelsokolov21 commented on src/components/UI-Kit/UISlider/Slider.jsx
> +  const hundleChange = (event) => setNum(event.target.value);
`handleChange`

2022-02-28 22:17 UTC, pavelsokolov21 commented on src/components/UI-Kit/UISlider/Slider.style.js
> +  &::-webkit-slider-thumb {
Тут кастомизация только для браузеров на `webkit`. Не заставляю что-то переделывать, но почитать про кроссбраузерность стоит. Для разных браузеров свои префиксы

2022-02-28 22:17 UTC, pavelsokolov21 commented on src/components/UI-Kit/UISlider/Slider.jsx
> +        primarySliderColor={primarySliderColor}
Мне кажется, эти названия не совсем тут подходят. Думаю, это не главный и побочный цвета, а просто два цвета: `first..., second...`

2022-02-28 22:18 UTC, KoTuK2306 commented on src/components/UI-Kit/UISlider/Slider.jsx
> +import React, { useState } from "react";
Я случайно

2022-02-28 22:18 UTC, KoTuK2306 commented on src/components/UI-Kit/UISlider/Slider.jsx
> +/* eslint-disable react/jsx-no-duplicate-props */
Тут тоже случайно

2022-02-28 22:18 UTC, KoTuK2306 commented on src/components/UI-Kit/UISlider/Slider.jsx
> +  const [num, setNum] = useState(50);
rangeRatio?

2022-03-01 11:58 UTC, pavelsokolov21 requested changes

2022-03-01 11:58 UTC, pavelsokolov21 commented on src/components/UI-Kit/UISlider/Slider.jsx
> +export const Slider = ({
Мне кажется, название `Slider` подразумевает карусель или что-то типа того. Я бы назван `RangeSlider` для ясности

2022-03-01 11:58 UTC, pavelsokolov21 commented on src/components/UI-Kit/UISlider/Slider.style.js
> +const sliderHeight = 5;
общие константы принято писать капсом `SLIDER_HEIGHT`

2022-03-01 11:58 UTC, pavelsokolov21 commented on src/components/UI-Kit/UISlider/Slider.style.js
> +  return (value / max) * 100;
Ты юзеру разрешает ввести отрицательные числа. Думаю, тут нужно сделать расчет процента по модулю, чтобы минус не сломал ничего

2022-03-01 11:58 UTC, pavelsokolov21 commented on src/components/UI-Kit/UISlider/Slider.style.js
> +    width: ${(props) => mutateThumbSize(props.size)};
повторение с кодом выше. Объедини в один

2022-03-01 11:58 UTC, pavelsokolov21 commented on src/components/UI-Kit/UISlider/Slider.style.js
> +    box-shadow: ${`0 0 0px 5px ${rgba("#969696", 0.5)}`};
повторение с кодом выше. Объедини

2022-03-02 15:34 UTC, pavelsokolov21 commented on src/components/constants/constants.js
> +export const RADIUS_RATIO = 2;
название `constants` в папке `constants` - это круто :)
Давай для файла придумаем что-нибудь более информативное?

Также, папку с константами не стоит держать в папке с компонентами.  Я бы вынес в папку `src`

2022-03-02 16:11 UTC, pavelsokolov21 approved these changes

2022-03-02 16:18 UTC, merged